# Generated by Django 3.1.6 on 2021-02-08 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0002_sport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_location', models.CharField(max_length=100)),
                ('match_date', models.DateTimeField()),
                ('score_team_1', models.IntegerField(default=0)),
                ('score_team_2', models.IntegerField(default=0)),
                ('id_sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bet.sport')),
                ('id_team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bet.team')),
                ('id_team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bet.team')),
            ],
        ),
    ]
