# Generated by Django 3.1.6 on 2021-02-08 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bet', '0003_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('document_number', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=22)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_value', models.DecimalField(decimal_places=3, max_digits=20)),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bet.customer')),
                ('id_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bet.match')),
                ('id_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='bet.team')),
            ],
        ),
    ]
